stages:
  - test
  - build


test:
  stage: test
  image: python:3.8
  script:
    - python3.8 -m venv venv
    - venv/bin/python -m pip install -r requirements-dev.txt
    - venv/bin/python -m pip install -e .[dev]
    - venv/bin/python -m pytest --cov=src --cov-report=term --cov-report=xml --junit-xml=report.xml
    - venv/bin/python -m mypy --no-error-summary docs src tests
    - venv/bin/python -m reuse lint
    - venv/bin/python -m ruff check docs src tests
    - venv/bin/python -m ruff format --diff docs src tests
    - venv/bin/sphinx-build docs public
  coverage: '/\d+\%\s*$/'
  artifacts:
    paths:
      - public
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml


build:
  stage: build
  image: python:3.8
  script:
    - python3.8 -m venv venv
    - venv/bin/python -m pip install build
    - venv/bin/python -m build .
  artifacts:
    paths:
      - dist


pages:
  stage: build
  image: python:3.8
  script:
    - ls public
  artifacts:
    paths:
      - public
  only:
    - master
